apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: camila-quispe-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-container
        image: camila/backend-transaccional:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: camila-quispe-configmap
        - secretRef:
            name: camila-quispe-secret
