apiVersion: v1
kind: Secret
metadata:
  name: camila-quispe-secret
  namespace: camila-quispe-ns
type: Opaque
stringData:
  SPRING_R2DBC_PASSWORD: "SuperSecretPass123!"
  SPRING_DATA_MONGODB_HOST: "192.168.49.1"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "Visons"
  SPRING_DATA_MONGODB_USERNAME: "admin"
  SPRING_DATA_MONGODB_PASSWORD: "adminpassword"
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: "admin"
