apiVersion: v1
kind: Secret
metadata:
  name: camila-quispe-secret
  namespace: camila-quispe-ns
type: Opaque
stringData:
  SPRING_R2DBC_PASSWORD: "SuperSecretPass123!"
  SPRING_DATA_MONGODB_URI: "mongodb://admin:adminpassword@192.168.49.1:27017/Visons?authSource=admin"
