apiVersion: v1
kind: Secret
metadata:
  name: diego-centeno-secret
  namespace: diego-centeno-ns
type: Opaque
stringData:
  SPRING_R2DBC_PASSWORD: "SuperSecretPass123!"
  # La URI base para conectar a MongoDB (usando adminpassword del .env)
  # Si luego cambias a MongoDB Atlas, solo actualizas este valor en el secreto.
  SPRING_DATA_MONGODB_HOST: "192.168.49.1"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "Visons"
  SPRING_DATA_MONGODB_USERNAME: "admin"
  SPRING_DATA_MONGODB_PASSWORD: "adminpassword"
  SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: "admin"
