apiVersion: v1
kind: Secret
metadata:
  name: diego-centeno-secret
  namespace: diego-centeno-ns
type: Opaque
stringData:
  SPRING_R2DBC_PASSWORD: "SuperSecretPass123!"
  # La URI base para conectar a MongoDB (usando adminpassword del .env)
  # Si luego cambias a MongoDB Atlas, solo actualizas este valor en el secreto.
  SPRING_DATA_MONGODB_URI: "mongodb://admin:adminpassword@192.168.49.1:27017/Visons?authSource=admin&directConnection=true"
