server:
  port: 9090

spring:
  application:
    name: backend-transaccional
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:sqlserver://host.minikube.internal:1433;database=Visons;encrypt=false}
    username: ${SPRING_R2DBC_USERNAME:sa}
    password: ${SPRING_R2DBC_PASSWORD:Password123!}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@host.minikube.internal:27017/Visons?authSource=admin}
