server:
  port: 9090

spring:
  application:
    name: backend-transaccional
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:sqlserver://192.168.49.1:1433;database=Visons;encrypt=false}
    username: ${SPRING_R2DBC_USERNAME:sa}
    password: ${SPRING_R2DBC_PASSWORD:Password123!}
  data:
    mongodb:
      host: 192.168.49.1
      port: 27017
      database: Visons
      username: admin
      password: adminpassword
      authentication-database: admin
