apiVersion: v1
kind: ConfigMap
metadata:
  name: lizeth-quispe-configmap
  namespace: lizeth-quispe-ns
data:
  SPRING_R2DBC_URL: "r2dbc:sqlserver://sqlserver:1433;database=Visons;encrypt=false"
  SPRING_R2DBC_USERNAME: "sa"
